version: '3.12'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - Medex1/docker.env
    volumes:
      - .:/srv/app
    ports:
      - '0.0.0.0:2500:2500'
    command: python manage.py runserver 0.0.0.0:2500

volumes:
  static-data:


